// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SocketIoSuave")>]
[<assembly: AssemblyProductAttribute("SocketIoSuave")>]
[<assembly: AssemblyDescriptionAttribute("Socket.IO implementation for Suave web server")>]
[<assembly: AssemblyVersionAttribute("0.2")>]
[<assembly: AssemblyFileVersionAttribute("0.2")>]
[<assembly: AssemblyCompanyAttribute("ITG")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SocketIoSuave"
    let [<Literal>] AssemblyProduct = "SocketIoSuave"
    let [<Literal>] AssemblyDescription = "Socket.IO implementation for Suave web server"
    let [<Literal>] AssemblyVersion = "0.2"
    let [<Literal>] AssemblyFileVersion = "0.2"
    let [<Literal>] AssemblyCompany = "ITG"
