// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SocketIoSuave.Tests")>]
[<assembly: AssemblyProductAttribute("SocketIoSuave")>]
[<assembly: AssemblyDescriptionAttribute("socket.io implementation for F# Suave webserver")>]
[<assembly: AssemblyVersionAttribute("0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SocketIoSuave.Tests"
    let [<Literal>] AssemblyProduct = "SocketIoSuave"
    let [<Literal>] AssemblyDescription = "socket.io implementation for F# Suave webserver"
    let [<Literal>] AssemblyVersion = "0.1"
    let [<Literal>] AssemblyFileVersion = "0.1"
